### PR TITLE
Implement IGetRealUIDBackend

### PR DESCRIPTION
**Pull request by bob4os**
If you are using lowercase in your SQL query to get users (as recommended in your tutorial) from the database, users will be able to login with for example "John Doe" even if their username is "john doe". (Expected and wanted behaviour.)

The problem is, Nextcloud will assume "John Doe" to be the correct username in this session and will set user IDs in various tables accordingly.

But - if you share a folder, Nextcloud will search for the username or displayname and will return "john doe" as username.
In the end, Nextcloud will end up with different spellings of your username in various tables, using them to create various paths, which do not match, resulting in users who won't see their shares, duplicate calendars, etc.

Implementing IGetRealUIDBackend should fetch the "correct" username at the beginning of the session and prevent further problems.

### CODE REVIEW

**Comment by bob4os** [comment]
I did some formatting.

What do you think of this patch?

**Comment by PanCakeConnaisseur** [comment]
Can you please elaborate the use case? What do you mean by "you are using lowercase in your SQL query" exactly? The example queries do not change the letter case. Only `get_users` is case insensitive but it does not write anything to the db.

**Comment by bob4os** [comment]
Currently the username is case-sensitive with this backend.

I'm using 'user_exists' => 'SELECT EXISTS(SELECT 1 FROM v_nextcloudlogin WHERE LOWER(Username) = LOWER( :username ))' in the Nextcloud config file.
After reading the documentation again I do see, that I misinterpreted your instructions in this part and mixed up two conditions - but:

If you want the login to be case-insensitive you cannot simply use the SQL query above, because if the username in the database is "john doe" and you use "John Doe" with uppercase initials, Nextcloud will use "John Doe" as uid in a variety of tables.

This results in:
If you share a folder and you use the search, 'get_users' => 'SELECT Username FROM v_nextcloudlogin WHERE (LOWER(Username) LIKE LOWER( :search )) OR (LOWER(Displayname) LIKE LOWER( :search ))' the backend will return "john doe" and share with "john doe", not with "John Doe".
But the user logged in as "John Doe" will never see the shared folder, because "John Doe" is not equal to "john doe".

If the user now uses "john doe" as username, he will see the share but a duplicate user (with resources) will be created for every possible upper-/lowercase combination of the username.

This pull request aims to solve this issue by getting the original value of the database table and always use this uid for every matching upper-/lowercase combination of the username entered by the user.

This pull request should also be backwards compatible, since your instructions required an exact match.
And this is also more in line with LDAP and Nextcloud native authentication which is case-insensitive too.

**Comment by PanCakeConnaisseur** [comment]
Thank you for the explanation! I think, I understand the advantage of having such a query now. Also thank you for the PR and the work you put in. I think it looks good in general, but needs some work before it can be merged.

IMHO some points that should be improved/changed:

- [ ] rewrite getRealUID() comment to have a single line description on top and a longer explanation below that, so you can quickly asses the purpose of the function, unless it is obvious from the name.
- [ ] rewrite getRealUID()'s comment to be easier to understand
- [ ] don't use the wording "this little function" because it does not communicate any useful information in this context
- [ ] can getUsers() potentially return more than one users? Can it happen that we have "john" and "John" in the database? I think you mentioned that Nextcloud is case-insensitive so that should not happen? Are we sure?
- [ ] use named parameter `limit` in getUsers() to make the code easier to understand
- [ ] why use `array_pop()` and not `realUID[0]`? Is there maybe a function that is even more descriptive?
- [ ] change `realUID` to a name that communicates that this is a set of elements and not only one
- [ ] the convention in Nextcloud seems to be to write `uid` in lower case letters
- [ ] the `@param` comment for $uid should contain a description that clarifies that this uid is the one that is being checked
- [ ] the thrown exception should give an explanation as to when it was thrown, to help debugging an error
- [ ] how could a test look like that would verify this new functionality?

Please address these issues or give me rights to add commits to this PR and I will try to do so myself. Thank you, I appreciate the work you have done.

**Comment by bob4os** [comment]
Thanks for looking at it.

I created the PR as a concept for discussion - not as finalized version.

Some answers to your arguments:
1-4. I simply copied the description from Nextcloud "lib/public/User/Backend/IGetRealUIDBackend.php" and oriented myself on "lib/private/User/Database.php", the description does explain itself - if you know where it is coming from, but it may be to specific and limited, agreed.
5. Nextcloud is case-insensitive with the username - I checked again yesterday.
Almost every authentication method I know is case-insensitive - I really hope that nobody is differentiating between "John" and "john" in this day and age. I cannot guarantee that.
You are right, since getUsers() does add wildcards there may be duplicates, it might be better to not use it and get it with another SQL statement like 'SELECT Username FROM v_nextcloudlogin WHERE LOWER(Username) = LOWER( :username )'.
6. We can do that.
7. Why not use array_pop()? In my opinion this function is descriptive...
8-9. I used realUID, because the name of the function is getRealUID() minus"get" and use camel-case...
10. We can do that.
11. Copied that from nextcloud, more specific information is always better - agreed.
12. To be honest, I do not have experience with this.

**Comment by PanCakeConnaisseur** [comment]
Another question came up when I started working on this PR:

1. How exactly do you end up with shares that are shared to to a variation of a username that differs in the case of the letters? I tried replicating this and when you select a user to share with, the Nextcloud UI returns a list of matching users and when you select one it is entered in the db with the correct case. AFAIU Nextcloud uses the correct cased UID -- so no problem here. I think if your `user_exists` query is case insensitive, then this is the problem. Is there a reason for that, which I am missing?
2. To retrieve the "real" UID, there should be an additional query. Do you agree?

So, after thinking about this further, I fail to see the necessity for this query, again.

**Comment by PanCakeConnaisseur** [comment]
Please ping me, if you want this reopened.

**Pull request closed without merging**
