### PR TITLE
Support nextcloud 16

### PR DESCRIPTION
**Pull request by jdsn**
Update proposal for nextcloud 16 support.
Hashes updated in 2nd commit.
Signature missing though :)

Fixes issue #15

### CODE REVIEW

**Comment by PanCakeConnaisseur** [comment]
@jdsn Thank you for the pull request, I will check whether the app still works with Nextcloud 16 and then do the update.

**Comment by jdsn** [comment]
I can confirm that the app still works in a production setup (with the same issues as before :smile: - will open issue or PR once I verified the reason)

**Comment by jdsn** [comment]
@PanCakeConnaisseur Any idea when you find time to update the app?

**Comment by PanCakeConnaisseur** [comment]
I just implemented the changes. I am following my own documented release steps, therefore it was easier for me to not use the PR, but I appreciate your input.

**Pull request closed without merging**
